import Head from 'next/head'
import { Inter } from 'next/font/google'
import useSWR from 'swr'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Index() {
  const { data, error } = useSWR('/api/staticdata', fetcher)
  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>
  return (
    <>
      <Head>
        <title>Pecege Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={inter.className}>
        <h1>Meus Produtos</h1>
        <ul>
          {data.map((item) => (
            <li>
              <p>{item.brand}</p>
              <p>{item.model}</p>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}
