import Head from 'next/head'

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Container from '@/components/Container'
import Article from '@/components/Article'

export default function Index() {
  return (
    <>
      <Head>
        <title>Pecege Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Sedgwick+Ave+Display&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Container>
        <Header />
        <Article />
        <Footer />
      </Container>
    </>
  )
}
